export const SET_COMPONENTS = 'SET_COMPONENTS';
export const SET_ICONS = 'SET_ICONS';
export const SET_FILTER_COUNT = 'SET_FILTER_COUNT';
export const SET_THEME = 'SET_THEME';
export const SET_SELECTED_ICON = 'SET_SELECTED_ICON';
export const SET_COMPONENT_DETAIL = 'SET_COMPONENT_DETAIL';